version: '3'


services:
  storage:
    image: minio/minio
    ports:
      - "9000:9000"  # S3 API port
      - "9001:9001"  # Web UI
    volumes:
      - ./backend/storage:/data  # Persistent shared storage
    environment:
      MINIO_ROOT_USER: minioadmin  # Default username
      MINIO_ROOT_PASSWORD: minioadminpassword  # Default password
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3